# Generated by Django 5.1.6 on 2025-02-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('PU Stone Panel', 'PU Stone Panel'), ('Sandwish Panel', 'Sandwish Panel'), ('WPC Panel', 'WPC Panel'), ('Aluco Board', 'Aluco Board'), ('Wooden Door', 'Wooden Door'), ('Cast Door', 'Cast Door'), ('Sintered Tiles', 'Sintered Tiles')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
