# Generated by Django 5.1.6 on 2025-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_branch_options_branch_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Interior Panel', 'Interior Panel'), ('Exterior Panel', 'Exterior Panel'), ('WPC Panel', 'WPC Panel'), ('Aluco Board', 'Aluco Board'), ('Wooden Door', 'Wooden Door'), ('Cast Door', 'Cast Door'), ('Sintered Tiles', 'Sintered Tiles')], max_length=20, null=True),
        ),
    ]
