# Generated by Django 5.1.6 on 2025-03-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_stock_branch_alter_branch_location_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
    ]
