# Generated by Django 5.1.6 on 2025-03-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_name_branch_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='name',
        ),
    ]
