# Generated by Django 5.1.6 on 2025-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_branch_name_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
