# Generated by Django 5.1.6 on 2025-03-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_order_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
