# Generated by Django 5.1.6 on 2025-03-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_sale_date_sale_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Interior Panels', 'Interior Panels'), ('Exterior Panels', 'Exterior Panels'), ('Aluco Board', 'Aluco Board'), ('Wooden Door', 'Wooden Door'), ('Cast Door', 'Cast Door'), ('Sintered Stone', 'Sintered Stone'), ('SPC Flooring Tile', 'SPC Flooring Tile'), ('UV Marble Sheet', 'UV Marble Sheet'), ('Sandwich Panel', 'Sandwich Panel'), ('3D Foam Sticker', '3D Foam Sticker'), ('PU Stone', 'PU Stone'), ('WPC Interlocking', 'WPC Interlocking'), ('PS Cornice', 'PS Cornice'), ('PS Skirting', 'PS Skirting'), ('Tiles', 'Tiles'), ('Artificial Grass', 'Artificial Grass'), ('Toilet', 'Toilet'), ('Roofing Sheets', 'Roofing Sheets'), ('Railings', 'Railings')], max_length=50, null=True),
        ),
    ]
