# Generated by Django 5.1.6 on 2025-03-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_invoice_customer_and_more'),
        ('user', '0005_alter_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.branch'),
        ),
    ]
